version: '3'

services:

  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "4800:4800"
    deploy:
      mode: replicated
      replicas: 1